version: "3.3"

services:
  table-tennis:
    image: ghcr.io/li-ninja/table-tennis:${TAG}
    ports:
      - 5650:8080
    restart: always
    container_name: ninja-table-tennis
    networks:
      #  set same network as the nginx service
      - my-network

networks:
  my-network:
    external: true
