import type { Metadata } from 'next';
import Header from '@/component/global/header';
import 'tw-elements-react/dist/css/tw-elements-react.min.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-2 mt-2">
        <Header />
        {children}
      </body>
    </html>
  );
}
